# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for f5321 configurations
Name: jolla-configuration-f5321
Requires:
- pattern:jolla-hw-adaptation-f5321
- pattern:jolla-configuration-loire

Summary: Jolla Configuration f5321

